# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy .NET app to Azure Web App - crashmap

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Set up Node.js (for client build)
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Build client application
        run: |
          cd crashmap.client
          npm ci
          npm run build

      - name: Restore .NET dependencies
        run: dotnet restore

      - name: Build .NET application
        run: dotnet build --no-restore --configuration Release

      - name: Run tests (if any)
        run: dotnet test --no-build --configuration Release --verbosity normal --logger trx --results-directory TestResults/
        continue-on-error: true

      - name: Publish .NET application
        run: dotnet publish crashmap.Server/crashmap.Server.csproj --configuration Release --output ./publish --no-restore --self-contained false

      - name: Create deployment package
        run: |
          cd ./publish
          zip -r ../deployment.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: deployment.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'crashmap'
          slot-name: 'Production'
          package: deployment.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_ABFE35D1F8E84249A9115A2F7F071174 }}